export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const CURRENT_MOVIES = "CURRENT_MOVIES";
export const GET_TRAILER_SUCCESS = "GET_TRAILER_SUCCESS";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";

